### ISSUE TITLE
Feature Request: add OpenGL capabilites

### ISSUE THREAD

**Issue by bsdooby** [nomad-software/tkd#46]
Sorry, I do not want to misuse the "Issues" section. But it would
be a nice extension if it were possible to have a modern OpenGL 
accelerated widget. Maybe throwing in some Tcl3D (http://www.tcl3d.org)?

**Comment by nomad-software** [comment]
It sounds an interesting idea but I think it would require too much work because you would have to port all the TCL OpenGL commands to D creating a sane API along the way. I don't really use D a whole lot anymore so I can't do it.

**Comment by bsdooby** [comment]
Thank you for replying to my request. I totally understand this. Are you willing to share why you do not use D anymore? Looks like you mostly use Go nowadays? Feel free to ignore this question...

**Comment by nomad-software** [comment]
I love D, I honestly think it's one of the best languages out there but it's going nowhere. Important bugs are taking years to fix, features are incomplete, libraries are nonexistent and the overall tooling is not very good. This is where Go shines. even though it's not a great language, the tooling and libraries are amazing and you get more done faster. It annoys me no end because I love D and I _want_ to use D.

**Comment by bsdooby** [comment]
That somehow resonates. And the reason why I (still) use C++/Tcl (which are getting better, too). 
Thank you for your honest response.
