### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by 1404er** [nomad-software/tkd#65]
Tried running the example with the
`dub --config=example` command, it gives me several warning of deprecated functions and then ends in an error:

`libcmt.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
.dub\build\example-debug-windows-x86_64-dmd_v2.098.1-dirty-7A28AC43C1B0C9E959EE4A53C170C61F\example.exe : fatal error LNK1120: 1 unresolved externals
Error: linker exited with status 1120
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.`

Am I doing something wrong or is this just out of date? I saw the last commit was october so I wasn't sure if this was even still maintained.

**Comment by jamiecarl** [comment]
I'm having this same problem.  Did you close this because you discovered the solution?  Care to share?  Thanks.

**Comment by nomad-software** [comment]
I'm sorry this project is no longer being maintained.

**Comment by jamiecarl** [comment]
> I'm sorry this project is no longer being maintained.

Well that's a bummer.  I was just assessing if this library would be a fit for a GUI project I need to undertake, and it was looking pretty good.

I did figure out how to overcome my problem in the end too.

For anyone else that has this problem and finds this issue, look here: https://wiki.dlang.org/D_for_Win32  You will need to modify the entrypoint into the application as described so that the linker can use the `/subsystem:windows` option.
